### ISSUE TITLE
Unexpected token (302 Page)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-corrector#2]
Kinder @ Ferrero
- 109 child brand product(s) found
- 24 product(s) to check
- 22.02% products ratio to check
- **************

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `parse': 757: unexpected token at '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> (JSON::ParserError)
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="http://world.openfoodfacts.org">here</a>.</p>
</body></html>
'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `parse'
    from /Library/Ruby/Gems/2.0.0/gems/openfoodfacts-0.3.0/lib/openfoodfacts/product.rb:152:in `update'
    from openfoodfacts-corrector.rb:77:in `block (3 levels) in run!'
    from openfoodfacts-corrector.rb:74:in `map'
    from openfoodfacts-corrector.rb:74:in `block (2 levels) in run!'
    from openfoodfacts-corrector.rb:71:in `each'
    from openfoodfacts-corrector.rb:71:in `block in run!'
    from openfoodfacts-corrector.rb:70:in `each'
    from openfoodfacts-corrector.rb:70:in `run!'
    from openfoodfacts-corrector.rb:96:in `<main>'
```

**Comment by nicolasleger** [comment]
I didn't succeed to reproduce your error, what command did you tipped (without password)? with which Ruby version? Thanks

**Comment by nicolasleger** [comment]
I finally succeed to reproduce without the default debug mode.

The problem was coming from endpoint subdomain changes for updates and some other errors from the `openfoodfacts` gem. Now it works again with the version `>= 0.3.1`.
